[project]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://prefix.dev/meta-forge", "conda-forge"]
description = "Add a short description here"
name = "pixi-cuda"
platforms = ["linux-64"]
version = "0.1.0"
[system-requirements]
cuda = "12.7"
libc = { family = "glibc", version = "2.28" }

[tasks]

[dependencies]
ai-edge = "*"
pip = "*"
opencv = "*"
ffmpeg = "*"
