[project]
authors = ["fecet <xiezej@gmail.com>"]
channels = [
  "nvidia/label/cuda-12.4.0",
  "nvidia",
  "pytorch",
  "conda-forge",
  "nodefaults",
]
description = "Add a short description here"
name = "pixi-cuda"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cuda = "12.4.*"
pytorch-cuda = "12.4.*"
cuda-driver-dev = "12.4.*"
cuda-version = { version = "12.4", channel = "nvidia" }
cudnn = { channel = "conda-forge" }
pytorch = "*"
torchaudio = "*"
torchvision = "*"
libjpeg-turbo = { channel = "conda-forge" }
python = "3.10.*"
ffmpeg = { channel = "conda-forge" }
opencv = ">=4.10"
