[project]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://prefix.dev/meta-forge", "conda-forge"]
description = "Add a short description here"
name = "pixi-cuda"
platforms = ["linux-64"]
version = "0.1.0"
[system-requirements]
cuda = "12.7"

[tasks]

[dependencies]
cuda = "12.6.*"
pytorch = { version = "==2.6.0", build = "*cuda*" }
torchvision = "*"
torchaudio = { version = "*", build = "*cuda*" }
python = "3.10.*"
pip = "*"
opencv = "*"
ffmpeg = "*"
