[project]
authors = ["fecet <xiezej@gmail.com>"]
channels = [
  "https://repo.prefix.dev/meta-forge",
  "conda-forge",
]
description = "Add a short description here"
name = "pixi-cuda"
platforms = ["linux-64"]
version = "0.1.0"
[system-requirements]
cuda = "12.7"

[tasks]

[dependencies]
cuda-cudart = "12.6.*"
pytorch = { version = "==2.5.1", build = "*cuda*" }
python = "3.10.*"
pip = "*"
opencv = "*"
torchaudio = { version = "==2.5.1", build = "*cuda*" }
ffmpeg = "*"
